# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 01:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advice',
            name='pub_date',
        ),
    ]
