# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=6)),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='advice',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='user',
        ),
    ]
