# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0004_auto_20160207_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
