# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0006_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=100)),
                ('user', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
