# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0008_auto_20160213_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
