# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0012_auto_20160214_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='guess',
            field=models.DateTimeField(verbose_name=['%a %b %d %Y %H:%M:%S %Z %z (PST)']),
        ),
    ]
