# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shower', '0014_auto_20160214_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='guess',
            field=models.TimeField(),
        ),
    ]
